name: Deploy to Netlify

on:
  push:
    branches: ["$default-branch"]

jobs:
  deploy:
    uses: My-IT-Guy-Organization/.github/.github/workflows/reusable-netlify-deploy.yml@main
    with:
      publish-dir: "."
      # build-command: "npm run build"
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
