name: Node CI

on:
  push:
    branches: ["$default-branch"]
  pull_request:

jobs:
  ci:
    uses: My-IT-Guy-Organization/.github/.github/workflows/reusable-node-ci.yml@main
    with:
      node-version: "20"
