name: Python CI

on:
  push:
    branches: ["$default-branch"]
  pull_request:

jobs:
  ci:
    uses: My-IT-Guy-Organization/.github/.github/workflows/reusable-python-ci.yml@main
    with:
      python-version: "3.12"
